Module 1 [Block 1- Day 2]
porag-m06/Hello-world pull request #1
Opened 2023-03-22 17:37 UTC by porag-m06

## Hello Microverse Project
Completed requirements are: 
- Created "Hello word" repo.
- Created branch "add-homepage"
- Added .gitignore file and added node-modules/ & test.md to it.
- Added and modified README form template
- Added index.html with the required header
- Added styles.css with text color modification of the header
- Added test.md flle

2023-03-22 18:03 UTC, mukhammadrizooff requested changes
Hi @porag-m06 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media0.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Highlights
- Correct GitHub Flow ✔️ 
- Good implementations ✔️ 
- Descriptive `PR` summary and `Commit` history ✔️ 

## Required Changes ♻️
- [ ] [REQUIRED] Good job so far! The linter result should be `green`. `AKA`: Linter should report `NO` errors, please fix your linter errors 🙏🏼 

![image](https://user-images.githubusercontent.com/63915024/226996523-3c3bae5d-6981-4a1f-8e91-c37f9ffbf924.png)


_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-22 18:03 UTC, mukhammadrizooff commented on README.md
> +## 👥 Authors <a name="authors"></a>
- [ ] [REQUIRED] It would be descriptive if you remove `-s` end of `Authors` word 👍🏼

2023-03-22 18:03 UTC, mukhammadrizooff commented on README.md
> +
- [REQUIRED] Kindly your `MIT` license is not working, please fix it 🙏🏼

2023-03-23 10:03 UTC, topeogunleye approved these changes
### Hi @porag-m06, 

# Status: Approved ✔️
Excellent job on making the changes requested by the previous code reviewer. Keep it up 👏

Your project is complete! There is nothing else to say other than... it's time to merge it 💪
Congratulations! 🎉
![congratulations](https://user-images.githubusercontent.com/52934128/163691476-087b4b9c-825b-40a3-85a1-d1bde44ffa53.gif)
>
## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Followed Github flow :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- PR has a good title and description :heavy_check_mark:
 
## [Optional] suggestions:
* Nothing to mention.
 
 _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
 
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.



------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-23 16:16 UTC, merged